# Travis CI Configuration File

# Tell Travis CI which distro to use
dist: trusty

# Tell Travis CI we're using PHP
language: php

# Run Matrix for these PHP versions
php:
- "5.6"
- "7.0"
- "7.2"
#- "7.0"
#  env: "SWITCH_TO_PHP=5.2"
#  dist: precise

# Setup a global environemnt and overide as needed
env:
# Run Matrix for these variables
- WP_MODE=single
- WP_MODE=multi
- WP_BRANCH=master
- WP_BRANCH=latest
- WP_BRANCH=previous
  global:
  - WP_TRAVISCI=phpunit

cache:
  directories:
   - $HOME/.composer/cache/files
   - $HOME/.cache/yarn
   - $HOME/.phpbrew

# Next we define our matrix of additional build configurations to test against.
# The versions listed above will automatically create our first configuration,
# so it doesn't need to be re-defined below.

matrix:
  include:
  - env: WP_TRAVISCI="yarn lint"
  - env: WP_TRAVISCI="yarn test-client"
  - env: WP_TRAVISCI="yarn test-gui"
  - env: WP_TRAVISCI="yarn danger ci"

# whitelist branches for the "push" build check.
branches:
  only:
    - master
    - master-stable
    - /^branch-.*$/
    - /^feature\/.*$/

# Clones WordPress and configures our testing environment.
before_script:
    - phpenv config-rm xdebug.ini
    - export PLUGIN_SLUG=$(basename $(pwd))
    - source ~/.nvm/nvm.sh
    - export PATH="$HOME/.composer/vendor/bin:$PATH"
    - |
        set -e
        source ./tests/install-php-phpunit.sh
        set +e
    - nvm install 8
    - nvm use 8
    - ./tests/prepare-wordpress.sh
    - mysql -e "set global wait_timeout = 3600;"

script:
    - echo "Running with the following versions:"
    - php -v
    - phpunit --version
    - ./tests/run-travis.sh

sudo: false

notifications:
   webhooks:
     urls:
       - https://betadownload.jetpack.me/travis.php
     on_success: always # Beta builder needs notifications for successful builds
   email:
     on_success: never # default: change
     recipients:
       - enej.bajgoric@automattic.com
       - georgestephanis@automattic.com
       - jeremy@automattic.com
       - miguel@automattic.com
       - rocco@automattic.com
       - smart@automattic.com
       - eric.binnion@automattic.com
       - allendav@automattic.com
       - beau@automattic.com
       - kraft@automattic.com
       - oscar@automattic.com
       # Encrypted Slack notification address.
       - secure: "WQdTdmYuifSW0hiJGXpQGKystMASC50QvxHlyUL5SM3h5GP8aCgeSsHuXvKPe3dT3Pffhk0dSHBfDtdWFwSHW/upURhg0vs4dm7+nxxvGZiTPzKcuAIjgvCoqWM7teyda/XqFGNSnv+XsT34uoyPhhFgd45T3oS+QQ3aNCruFak="

addons:
  code_climate:
    repo_token: 683bd559e5214ca3b721092af177893f05765ba90d2589fcf35d7e85c6ea01e8
